# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, unstable-pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  hardware.enableAllFirmware = true;
  hardware.enableRedistributableFirmware = true;
  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "snd-mixer-oss" "k10temp" ];
  boot.extraModulePackages = [ ];
  boot.kernelPackages = unstable-pkgs.linuxPackages_zen;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a405280b-55f1-47fa-abdf-56033c2af941";
    fsType = "btrfs";
    options = [ "compress=zstd" "subvol=root" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a405280b-55f1-47fa-abdf-56033c2af941";
    fsType = "btrfs";
    options = [ "compress=zstd" "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/a405280b-55f1-47fa-abdf-56033c2af941";
    fsType = "btrfs";
    options = [ "compress=zstd" "noatime" "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
  };
  fileSystems."/var/lib/MoneroNode" = {
    device = "/dev/disk/by-uuid/6dc6e2c5-720a-44d4-84c0-2cf9b2ecdffb";
    fsType = "ext4";
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
